import type { Metadata } from "next"
import { SiteHeader } from "@/components/site-header"
import { SiteFooter } from "@/components/site-footer"
import { DOWNLOAD_URL } from "@/lib/links"

export const metadata: Metadata = { title: "Microsoft Office Viewer Alternative for Windows", description: "A free, portable alternative to the discontinued Microsoft Word, Excel, and PowerPoint viewers. Open DOCX, XLSX, and PPTX files without Microsoft Office.", alternates: { canonical: "https://eleviewer.vercel.app/alternatives/microsoft-office-viewer" } }

const rows = [["DOCX files", "Yes", "Word Viewer discontinued"], ["XLSX files", "Yes", "Excel Viewer discontinued"], ["PPTX files", "Yes", "PowerPoint Viewer discontinued"], ["Portable .exe", "Yes", "No"], ["Admin rights", "Not required", "Varies by setup"], ["Offline use", "Yes", "Depends on app"]]

export default function MicrosoftOfficeViewerAlternative() { const jsonLd = { "@context": "https://schema.org", "@type": "Article", headline: "Microsoft Office Viewer Alternative for Windows", description: metadata.description, url: "https://eleviewer.vercel.app/alternatives/microsoft-office-viewer" }; return <div className="flex min-h-screen flex-col bg-background text-foreground"><SiteHeader /><main id="main-content" className="flex-1"><article className="mx-auto max-w-4xl px-5 py-16 sm:py-24"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} /><p className="inline-flex items-center rounded-full border border-border bg-panel px-3 py-1 font-mono text-xs font-medium uppercase tracking-wider text-muted-foreground">Alternative guide</p><h1 className="mt-5 max-w-3xl text-balance text-3xl font-bold tracking-tight sm:text-5xl">A free alternative to Microsoft Office Viewer</h1><p className="mt-5 max-w-2xl text-pretty text-base leading-7 text-muted-foreground">Microsoft Word Viewer, Excel Viewer, and PowerPoint Viewer were discontinued. EleViewer gives Windows users one portable app for opening common Office files without buying or installing Microsoft Office.</p><div className="mt-10 overflow-x-auto rounded-xl border border-border"><table className="w-full min-w-[520px] text-left text-sm"><caption className="sr-only">EleViewer compared with discontinued Microsoft viewers</caption><thead className="bg-panel text-muted-foreground"><tr><th className="p-4 font-medium">Capability</th><th className="p-4 font-medium">EleViewer</th><th className="p-4 font-medium">Old Microsoft viewers</th></tr></thead><tbody>{rows.map(([feature, eleviewer, microsoft]) => <tr key={feature} className="border-t border-border"><th className="p-4 font-medium">{feature}</th><td className="p-4 text-muted-foreground">{eleviewer}</td><td className="p-4 text-muted-foreground">{microsoft}</td></tr>)}</tbody></table></div><section className="mt-12 rounded-xl border border-border bg-panel/50 p-6"><h2 className="text-xl font-semibold">Which files can it open?</h2><p className="mt-3 leading-7 text-muted-foreground">EleViewer supports DOCX, XLSX, PPTX, PDF, Markdown, CSV, HTML, and TXT. It also includes PDF Read Aloud, local course folders, session restore, and a built-in browser panel.</p><a href={DOWNLOAD_URL} className="mt-6 inline-flex h-11 items-center justify-center rounded-lg bg-primary px-6 text-sm font-medium text-primary-foreground transition-opacity hover:opacity-90">Download EleViewer</a></section></article></main><SiteFooter /></div> }
