import type { Metadata } from "next"
import { notFound } from "next/navigation"
import { SiteHeader } from "@/components/site-header"
import { SiteFooter } from "@/components/site-footer"
import { DOWNLOAD_URL } from "@/lib/links"

const useCases = {
  students: { title: "Document Viewer and Study Workspace for Students", description: "A free Windows study workspace for students who need PDFs, Word files, slides, spreadsheets, and notes in one offline app.", answer: "EleViewer helps students keep readings, assignments, slides, and notes together. It opens common formats locally, reads PDFs aloud, remembers your place, and needs no Microsoft Office account.", points: ["Open PDF, DOCX, XLSX, PPTX, Markdown, CSV, HTML, and TXT files", "Use Read Aloud for hands-free reading", "Add a local course folder with the Vault sidebar", "Study offline with zero telemetry and no account"] },
  "offline-study": { title: "Offline Study App for Windows", description: "Study without Wi-Fi in a local-first Windows app for readings, notes, spreadsheets, and course folders.", answer: "EleViewer is an offline study app for Windows 10 and 11. Once downloaded, it can open supported local files without an internet connection, account, or cloud upload.", points: ["Keep course material on your own computer", "Search local files with the Vault Explorer", "Restore tabs and reading positions", "Use native Windows voices for offline Read Aloud"] },
  "school-computers": { title: "Portable Document Viewer for School Computers", description: "Open course files on shared or locked-down Windows computers with a portable app that needs no installer or admin rights.", answer: "EleViewer is designed for computers where you cannot install software. Copy the single portable .exe to an accessible folder or USB drive and open documents without system-wide changes.", points: ["No administrator privileges required", "No traditional installer or account", "Works with common Office and document formats", "Open source code is available for review"] },
} as const

type UseCaseSlug = keyof typeof useCases
export function generateStaticParams() { return Object.keys(useCases).map((slug) => ({ slug })) }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const item = useCases[slug as UseCaseSlug]; if (!item) return {}; return { title: item.title, description: item.description, alternates: { canonical: `/use-cases/${slug}` } } }

export default async function UseCasePage({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const item = useCases[slug as UseCaseSlug]; if (!item) notFound(); const jsonLd = { "@context": "https://schema.org", "@type": "Article", headline: item.title, description: item.description, url: `https://eleviewer.vercel.app/use-cases/${slug}`, author: { "@type": "Organization", name: "EleViewer" } }; return <div className="flex min-h-screen flex-col bg-background text-foreground"><SiteHeader /><main id="main-content" className="flex-1"><article className="mx-auto max-w-4xl px-5 py-16 sm:py-24"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} /><p className="inline-flex items-center rounded-full border border-border bg-panel px-3 py-1 font-mono text-xs font-medium uppercase tracking-wider text-muted-foreground">Use case</p><h1 className="mt-5 max-w-3xl text-balance text-3xl font-bold tracking-tight sm:text-5xl">{item.title}</h1><p className="mt-5 max-w-2xl text-pretty text-base leading-7 text-muted-foreground">{item.description}</p><section className="mt-10 rounded-xl border border-border bg-panel/50 p-6"><h2 className="text-xl font-semibold">Who is EleViewer for?</h2><p className="mt-3 leading-7 text-muted-foreground">{item.answer}</p></section><section className="mt-12"><h2 className="text-2xl font-semibold">What you can do</h2><ul className="mt-5 grid gap-3 sm:grid-cols-2">{item.points.map((point) => <li key={point} className="rounded-lg border border-border p-5 text-sm leading-6"><span className="mr-2 text-accent">+</span>{point}</li>)}</ul></section><a href={DOWNLOAD_URL} className="mt-10 inline-flex h-11 items-center justify-center rounded-lg bg-primary px-6 text-sm font-medium text-primary-foreground transition-opacity hover:opacity-90">Download the portable app</a></article></main><SiteFooter /></div> }
